baseURL: "https://not-a-number.io/"
languageCode: en-us
title: Not a Number
theme:
  - hugo-notice
  - hugo-loremipsum
  - hugo-redirect
summaryLength: 50
disqusShortname: drupol
enableGitInfo: true
permalinks:
  posts: "/:year/:title"
  page: "/:slug/"

pagination:
  pagerSize: 10

menu:
  navbar:
    - name: About
      url: /about
      weight: 10

    - name: Projects
      url: /projects
      weight: 20

    - name: Sponsor my work
      url: /sponsor
      weight: 30

    - name: Bookshelf
      url: /bookshelf
      weight: 40

    - name: CV
      url: /cv
      weight: 50

params:
  author: Pol Dellaiera
  authoremail: pol.dellaiera@protonmail.com
  tagline: NaN
  logo: /static/logo.svg
  favicon: /static/logo.svg
  readingTime: true
  wordCount: true
  hideAuthor: true
  description: |
    Welcome to my unique repository of divergent sequences of random characters.
    Here, you may contemplate the endless variations of 26 letters and some special characters.
  header_visible: true
  date_format: "Mon Jan 02, 2006"
  sharingicons: true
  truncate: true
  DefaultContentLanguage: en
  github: drupol

ignoreErrors:
  - "error-remote-getjson"

params.google.analytics:
  id: "G-7PNPX0VZXC"
