baseURL: 'https://not-a-number.io/'
languageCode: en-us
title: Not a Number
theme:
  - hugo-notice
  - hugo-loremipsum
  - hugo-redirect
paginate: 10
summaryLength: 50
googleAnalytics: UA-97356033-1
disqusShortname: drupol
enableGitInfo: true
permalinks:
  posts: '/:year/:title'
  page: '/:slug/'

menu:
  navbar:
    - name: About
      url: /about
      weight: 10

    - name: Projects
      url: /projects
      weight: 20

    - name: Bookshelf
      url: /bookshelf
      weight: 30

    - name: CV
      url: /cv
      weight: 40

author:
  name: "Pol Dellaiera"

params:
  author: Pol Dellaiera
  authoremail: pol.dellaiera@protonmail.com
  tagline: NaN
  logo: /static/logo.svg
  favicon: /static/logo.svg
  readingTime: true
  wordCount: true
  hideAuthor: true
  description: |
    Welcome to my repository of non-convergent suite of random letters.
    Here, you may contemplate the variation of 26 letters and some other weird characters.
  header_visible: true
  date_format: "Mon Jan 02, 2006"
  sharingicons: true
  truncate: true
  DefaultContentLanguage: en
  github: drupol
  twitter: drupol
