[build]
publish = "public"
command = "hugo -b $URL --gc --minify --themesDir themes/"

[build.environment]
HUGO_VERSION = "0.102.3"

[context.deploy-preview]
command = "hugo -b ${DEPLOY_PRIME_URL} -F"
